openshift/assisted-image-service

OWNERS
OWNERS_ALIASES

This allows prow to play nicely with the project.

chore: add OWNERS and OWNERS_ALIASES files

---

Makefile
README.md
main.go
skipper.yaml

Rename `Port` to `ListenPort` and document `ASSISTED_SERVICE_HOST` format for clarification
N/A
/cc @carbonin
As discussed in https://github.com/openshift/assisted-image-service/pull/9#discussion_r690367195

Rename `Port` to `ListenPort` and document `ASSISTED_SERVICE_HOST` format for clarification

---

internal/handlers/images.go
internal/handlers/images_test.go

When asking the assisted-service for the discovery.ign, use the /v2/infra-envs API.
Manual testing using assisted-service running in minikube.
/cc @carbonin 
/cc @

move to v2 api for discovery ignition

---

internal/handlers/images.go
internal/handlers/images_test.go
pkg/isoeditor/stream.go
pkg/isoeditor/stream_test.go

This PR uses the work from https://github.com/openshift/assisted-service/pull/2342 to get the initrd content for a particular image and nests the ignition overlay reader into an additional one for embedding the initrd.
Once https://github.com/openshift/assisted-service/pull/2342 is merged I'll test an image built from this branch against a locally deployed assisted service and ensure the image is created correctly.
/cc @djzager 
JIRA task: https://issues.redhat.com/browse/MGMT-7500
Depends on: https://github.com/openshift/assisted-service/pull/2342

Query initrd content and embed into minimal isos

---

.dockerignore

Ignore `Dockerfile` to avoid cache invalidation when making changes to it.
Signed-off-by: Flavio Percoco <flaper87@gmail.com>
Manual test 
/cc @carbonin

NO-ISSUE: Ignore Dockerfile when copying files to image

---

Dockerfile.image-service

Using latest may lead us to unexpected and undesired surprises. Let's try to keep track of
the major and minor versions we build from, and keep all the images aligned
Signed-off-by: Flavio Percoco <flavio@redhat.com>
Manual build of the image
/cc @carbonin 
/cc @djzager

MGMT-7762: Pin the UBI version to 8.4

---

README.md

Previously the list of parameters wasn't formatted as a list and was getting put all on one line which made it really hard to read.
N/A
/cc @djzager 
/cc @

NO-ISSUE: Fix typo and formatting in readme

---

OWNERS_ALIASES

This removes people who are no longer on the team and generally makes it match the file in openshift/assisted-service
/cc @rollandf 
/cc @filanov

NO-ISSUE: Update owners file

---

Makefile

Use the edge-infrastructure image instead of the ocpmetal one
N/A
/cc @lranjbar 
/cc @osherdp

Use edge-infrastructure image instead of ocpmetal

---

internal/handlers/images.go
internal/handlers/images_test.go

Previously when the call to assisted service to fetch either the
ignition or initrd failed in any way (including 4xx errors) the image
service would return a 500.
After this commit the image service returns the same return code as
assisted service when the call to assisted service fails.
Unit tests updated and ran the image service locally against stage.
Created an infra-env in the stage environment and crafted a url to the locally running image service that would download the image for the newly created infra-env.
Downloaded the image successfully, then tested that the same request, but with an incorrect token returned a 401.
/cc @rollandf 
https://issues.redhat.com/browse/MGMT-8420

Pass the status code through when assisted service request fails

---

pkg/imagestore/imagestore.go
pkg/imagestore/imagestore_test.go

In order to support multiple images with the same build version, included openshift_version in the iso image name to avoid a conflict. This is required to support multiple x.y.z versions of openshift, while keeping the x.y images. I.e. x.y and x.y.z might refer to the same build version.
Added/modified relevant tests in imagestore_test.
/cc @carbonin 
/cc @filanov

MGMT-8661: Added openshift_version to image path template

---

pkg/imagestore/imagestore.go

http.DefaultTransport has some useful properties set that are not
present in a zero-value transport struct.
Specifically it sets up a function for fetching proxy environment
variables.
When we moved from using the default transport to creating our own to
solve https://bugzilla.redhat.com/show_bug.cgi?id=2034686 we also
removed the proxy environment variable handling as a side-effect.
This is a backport to ocm-2.4 of https://github.com/openshift/assisted-image-service/pull/61
/cc @filanov 
https://bugzilla.redhat.com/show_bug.cgi?id=2069806

[release-ocm-2.4] Bug 2069806: Use fields from http.DefaultTransport in imagestore

---

Dockerfile.image-service

Incorporate fix for CVE-2022-0778
/cc @CrystalChun

Update openssl libs in Dockerfile

---

internal/handlers/assisted_service_client.go
internal/handlers/initrd.go
internal/handlers/initrd_test.go
internal/handlers/iso.go
internal/handlers/iso_test.go

This time is based on the last modified time sent to the service when
querying for the ignition from assisted-service.
This will be used by the ironic cache to determine when it needs to
re-download an image. Before this change the image would be
re-downloaded every time a host booted, but now the cache will start
acting like a cache.
Deployed assisted service and this image service branch locally and observed `Last-Modified` header on iso downloads matching the InfraEnv updated_at time.
/cc @flaper87 
https://issues.redhat.com/browse/MGMT-7274

Set Last-Modified time for iso and initrd downloads

---

internal/handlers/initrd.go
internal/handlers/initrd_test.go

Originally it was thought that this would not be necessary as iPXE requires network access to work. This became an issue when working with ironic though.
In order to configure iPXE for the hosts it is trying to boot ironic controlls DHCP, and therefore DNS, for those hosts. The problem is that they don't forward DNS requests to any DNS servers that happen to already be configured in the environment.
Adding the static networking config to the initrd artifact will enable a workaround for this issue where the user would provide DNS configuration to the hosts using nmstate even if that configuration was already present in the environment.
Built and applied this patch to an environment with the ironic issue described in :point_up: 
Applied an nmstate configuration to the infraEnv and the host …

MGMT-12189: Include static network config in initrd pxe artifact

---

integration_test/images_test.go
internal/handlers/assisted_service_client.go
internal/handlers/iso_test.go

MGMT-12545: Rename "discovery kernel arguments" to "kernel arguments" in infra-env context

---

pkg/imagestore/imagestore.go
pkg/imagestore/imagestore_test.go

Before this change a user could add a non-rhcos/fcos ISO to our image list and we would fail in unpredictable ways with unhelpful error messages. This commit explicitly validates the volume ID on the downloaded ISO to ensure we're dealing with something we support.
With this change the image service fails with a clear error message when configured with an unsupported ISO:
```
{"file":"/go/src/github.com/openshift/origin/pkg/imagestore/imagestore.go:210","func":"github.com/openshift/assisted-image-service/pkg/imagestore.(*rhcosStore).Populate.func1","level":"error","msg":"failed to validate /data/rhcos-full-iso-4.8-48.84.202109241901-0-x86_64.iso: ISO volume identifier (Fedora-S-dvd-x86_64-37) is invalid","time":"2022-12-02T15:00:52Z"} …
```

Validate the volume ID for downloaded ISOs

---

deploy/template.yaml

Add temporary 4.13 RHCOS image to the console deploy template
/cc @osherdp 
/cc @gamli75

MGMT-13327: MGMT-13300: Add support for 4.13 by duplicating 4.12 images

---

integration_test/images_test.go
pkg/imagestore/imagestore.go
pkg/imagestore/imagestore_test.go
pkg/isoeditor/kargs_test.go
pkg/isoeditor/rhcos.go

Allow images with "scos-" volume ID. This is required to setup OKD SCOS via Assisted Installer
Manual run
/cc @carbonin 
/cc @

validateISOID: allow SCOS images

---

Dockerfile.image-service

In order to be FIPS compliant, we need to compile
all go code with CGO_ENABLED=1.
Waiting for e2e CI tests to complete.
/cc @carbonin 
/cc @filanov 
https://issues.redhat.com/browse/MGMT-15235

MGMT-15235: Compile with CGO_ENABLED=1 for FIPS

---

pkg/servers/servers.go

fix for vulnerability [GO-S2112](https://app.deepsource.com/directory/analyzers/go/issues/GO-S2112) 
this is for updating go linter  and fixing PR #133
/cc @carbonin

NO-ISSUE: fix for vulnerability GO-S2112

---

pkg/isoeditor/rhcos.go

Generate minimal ISO for agent installer similar to the assisted installer by removing the rootfs image file. There are minor differences compared to the existing method for assisted installer such as 
- The agent installer will provide the value for volume ID at the time of invocation
- When `CreateMinimalISO()` is invoked from the agent installer, the agent installer provides the location of extracted files via `extractDir` so `CreateMinimalISO` does not need to extract the ISO whereas the assisted installer will first extract the ISO in `CreateMinimalISOTemplate()` and then call `CreateMinimalISO()`
/cc @
/cc @
https://issues.redhat.com/browse/AGENT-702

AGENT-702: Generate minimal ISO for agent installer

---

OWNERS_ALIASES

Add my github account as owner for this repository
No tests needed
/cc @rccrdpccl 
/cc @adriengentil

NO-ISSUE: Add my github account as owner for this repository

---

OWNERS_ALIASES

NO-ISSUE: add rccrdpccl to approvers

---

deploy/template.yaml

Update image service images
No tests
/cc @gamli75 
/cc @adriengentil

NO-ISSUE: Update images

---

OWNERS_ALIASES

NO-ISSUE remove filanov from approves

---

main.go

During the implementation of [MGMT-16507](https://issues.redhat.com//browse/MGMT-16507) the incorrect CA cert was passed into the ImageStore This PR corrects that by fixing the reference
/cc @
/cc @
- [] Does this change include unit tests (note that code changes require unit tests)

MGMT-16507: Fix incorrect reference to ImageStore

---

OWNERS_ALIASES

NO-ISSUE: add missing accounts for PR approvals

---

README.md
internal/handlers/handlers_suite_test.go
internal/handlers/images.go
internal/handlers/images_test.go
internal/handlers/initrd.go
internal/handlers/initrd_addrsize.go
internal/handlers/initrd_addrsize_test.go
main.go

Reopening #204 on behalf of @AmadeusPodvratnik
The previous PR got stuck because of a Konflux CI issue

MULTIARCH-4515: add new endpoint to receive initrd.addrsize

---

OWNERS_ALIASES

NO-ISSUE: Add pastequo as approver

---

.tekton/assisted-image-service-saas-main-pull-request.yaml
.tekton/assisted-image-service-saas-main-push.yaml
Dockerfile.image-service

* Add labels
* Add default user
* Add licenses under /licenses/
Requirements come from https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#additional_resources and would prevent us from releasing an image (we have an exception for "based_on_ubi image")
/cc @rccrdpccl 
/cc @adriengentil

KONFLUX-1611: Add labels, licenses & user to Dockerfile

---

Dockerfile.image-service

- update golang to 1.21
- 
/cc @
/cc @

MGMT-18385 - updating golang to 1.21

---

.tekton/assisted-image-service-saas-main-pull-request.yaml
.tekton/assisted-image-service-saas-main-push.yaml

Task will become mandatory to release, starting Novermber 1st
/cc @
/cc @

MGMT-19174: Add rpms-signature-scan to Konflux pipeline

---

pkg/isoeditor/rhcos.go
pkg/isoeditor/rhcos_test.go

MGMT-18577: Change the minimal version for nmstate

---

Dockerfile.image-service-mce

As part of migrating to konflux, we need to update our downstream dockerfiles for mce and put them in our upstream repos.
/cc @pastequo 
Part-of [MGMT-19371](https://issues.redhat.com//browse/MGMT-19371)

MGMT-19371: Add downstream dockerfile for mce

---

.tekton/assisted-image-service-mce-downstream-main-pull-request.yaml
.tekton/assisted-image-service-mce-downstream-main-push.yaml

Update the tekton pipelines used to build mce downstream images to be multi-arch.
/cc @
/cc @
Part-of [MGMT-19390](https://issues.redhat.com//browse/MGMT-19390)

MGMT-19390: Update mce's tekton pipelines to be multi-arch

---

.tekton/assisted-image-service-mce-downstream-2-13-pull-request.yaml
.tekton/assisted-image-service-mce-downstream-2-13-push.yaml

This will finish the onboarding process for acm 2.13
/cc @pastequo
/cc @
Part-of [MGMT-19408](https://issues.redhat.com//browse/MGMT-19408)

MGMT-19408: Create tekton pipelines for acm 2.13

---

.tekton/assisted-image-service-saas-main-pull-request.yaml
.tekton/assisted-image-service-saas-main-push.yaml

Remove deprecated task sbom-json-check
/cc @
Closes [MGMT-19531](https://issues.redhat.com//browse/MGMT-19531)

MGMT-19531: Remove deprecated task sbom-json-check

---

.tekton/assisted-image-service-mce-downstream-2-13-pull-request.yaml
.tekton/assisted-image-service-mce-downstream-2-13-push.yaml
.tekton/assisted-image-service-mce-downstream-main-pull-request.yaml
.tekton/assisted-image-service-mce-downstream-main-push.yaml
.tekton/assisted-image-service-saas-main-pull-request.yaml
.tekton/assisted-image-service-saas-main-push.yaml
Dockerfile.image-service-mce
rpm-prefetching/README.md
rpm-prefetching/rpms.in.yaml
rpm-prefetching/rpms.lock.yaml

Configure the following things for releasing in konflux:
- Hermetic builds
- Pushing source image.
- Adding label io.openshift.tags.
- Setting up snyk
/cc @
/cc @
Part-of [MGMT-19645](https://issues.redhat.com//browse/MGMT-19645)

MGMT-19645: Configure a few things for releasing in konflux

---

renovate.json

Tune renovate config to add required labels for auto merge
/cc @
/cc @

MGMT-19734: Tune renovate config to enable auto merge

---

.tekton/assisted-image-service-acm-ds-2-14-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-14-push.yaml

Now downstream images are built with Kofnflux, therefore we change the references in the master branch to ocm-2.14.
/cc @danmanor 
/cc @giladravid16

MGMT-19950: Modify Konflux YAMLs to ocm-2.14

---

README.md

Trigger new image promotion to `ocm2.14`

NO-ISSUE: Trigger new image promotion to ocm-2.14 in CI

---

README.md

Reverts openshift/assisted-image-service#346

Revert "NO-ISSUE: Trigger new image promotion to ocm-2.14 in CI"

---

integration_test/images_test.go

/cc @gamli75 
/cc @adriengentil

NO-ISSUE: Fix unit-test downloading ISO from pre-release stream which its path has changed

---

OWNERS_ALIASES

Eran has left Assisted Installer team

[release-ocm-2.13] NO-ISSUE: Remove eran ifrach account from OWNERS

---

.tekton/assisted-image-service-acm-ds-2-14-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-14-push.yaml
.tekton/assisted-image-service-acm-ds-main-pull-request.yaml
.tekton/assisted-image-service-acm-ds-main-push.yaml
.tekton/assisted-image-service-saas-main-pull-request.yaml
.tekton/assisted-image-service-saas-main-push.yaml

SAST tasks will become mandatory the 1st of April
/cc @
/cc @

MGMT-20149: Add sast required tasks in Konflux

---

.tekton/assisted-image-service-acm-ds-2-13-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-13-push.yaml

SAST task will become mandatory the 1st of April
/cc @
/cc @

MGMT-20149: Add required SAST tasks

---

.tekton/assisted-image-service-acm-ds-2-14-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-14-push.yaml
.tekton/assisted-image-service-acm-ds-main-pull-request.yaml
.tekton/assisted-image-service-acm-ds-main-push.yaml
.tekton/assisted-image-service-saas-main-pull-request.yaml
.tekton/assisted-image-service-saas-main-push.yaml
pkg/imagestore/imagestore_test.go
testregex.py

[MGMT-19567](https://issues.redhat.com//browse/MGMT-19567): This is a test PR to test the 2 staged CI jobs. The branch is also a test branch so no harm can be done.
expected behavior:
- when lgtm is added the second stage jobs will trigger and if they are successful a merge is possible
- /test remaining-required is not working since it's an automated pipeline
/cc @
/cc @

MGMT-19567: Test1

---

.tekton/assisted-image-service-acm-ds-2-15-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-15-push.yaml

NO-ISSUE: Modify Konflux YAMLs to ocm-2.15

---

.tekton/assisted-image-service-acm-ds-2-15-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-15-push.yaml

NO-ISSUE: Add konflux service account migration

---

.tekton/assisted-image-service-acm-ds-2-14-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-14-push.yaml

Konflux Service Account Migration
/cc @
/cc @

NO-ISSUE: CI Konflux SA migration

---

pkg/imagestore/imagestore.go

NO-ISSUE: Test

---

.tekton/assisted-image-service-acm-ds-2-15-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-15-push.yaml
.tekton/assisted-image-service-acm-ds-main-pull-request.yaml
.tekton/assisted-image-service-acm-ds-main-push.yaml

ACM-21380: Make ACM builds multi-arch

---

.tekton/assisted-image-service-acm-ds-2-13-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-13-push.yaml

MGMT-20858: apply tags migration

---

integration_test/images_test.go
main.go
pkg/imagestore/imagestore.go
pkg/imagestore/imagestore_test.go
pkg/isoeditor/mock_nmstate_handler.go
pkg/isoeditor/nmstate_handler.go
pkg/isoeditor/nmstate_handler_test.go
pkg/isoeditor/rhcos.go
pkg/isoeditor/rhcos_test.go

This is a manual cherry-pick of https://github.com/openshift/assisted-image-service/pull/462
/assign linoyaslan

[release-ocm-2.13] MGMT-21276: Add nmstatectl binary for the s390x arch

---

.tekton/assisted-image-service-acm-ds-2-11-pull-request.yaml
.tekton/assisted-image-service-acm-ds-2-11-push.yaml
Dockerfile.image-service-mce
rpm-prefetching/README.md
rpm-prefetching/rpms.in.yaml
rpm-prefetching/rpms.lock.yaml

Configure konflux pipelines for ACM 2.11
/cc @
/cc @

NO-ISSUE: Configure konflux pipelines for ACM 2.11

---

rpm-prefetching/rpms.lock.yaml

NO-ISSUE: Update rpms.lock.yaml
