openshift/assisted-image-service

Dockerfile.image-service-build, Makefile, hack/setup_env.sh
Both the prow test container and our build container will need to
install the same test dependencies and we want to keep those as similar
as possible.
After this is merged, the prow test-bin container will call the new
`build-openshift-ci-test-bin` make target to ensure our dependencies are
installed
This also adds the `genisoimage` command in preparation of the tests
from the iso editing code.
Required for https://github.com/openshift/assisted-image-service/pull/5 to pass tests
cc @lranjbar
=> Add setup script to share logic with prow

pkg/isoeditor/isoeditor_suite_test.go, pkg/isoeditor/isoutil_test.go, pkg/isoeditor/rhcos_test.go
Both isoutil_test and rhcos_test need an iso and some test files.
There were slight differences between what was being used, but there's
no reason this setup can't be shared.
This commit DRYs up the setup for these test files and also removes some
global state from the rhcos tests.
=> Clean up test setup duplication

build_deploy.sh
Adds a build file similar to the [one in assisted-service](https://github.com/openshift/assisted-service/blob/165e849305ecb67cc6b1b24ccb76137c10693f53/build_deploy.sh)
https://issues.redhat.com/browse/MGMT-7255
=> Add build_deploy.sh script to create app-sre image

Makefile, README.md, internal/handlers/images.go, internal/handlers/images_test.go, main.go
We will either pass this token in another query parameter or as a header
depending on the value of the `REQUEST_AUTH_TYPE` env var.
https://issues.redhat.com/browse/MGMT-7499
=> MGMT-7499 Take an auth token as a query parameter and pass it to assisted

build_deploy.sh
It looks like the app-sre automation we're using for building the image doesn't have an option to use podman. So just change the script to use docker and see if that works.
N/A
/cc @djzager 
/cc @omertuc 
Logs from previous job:
```
11:30:41 [openshift-assisted-image-service-gh-build-main] $ /bin/sh -xe /tmp/jenkins2921027276091833060.sh
11:30:41 + ./build_deploy.sh
11:30:41 ++ git rev-parse --short=7 HEAD
11:30:41 + TAG=1f34613
11:30:41 + REPO=quay.io/app-sre/assisted-image-service
11:30:41 + export IMAGE=quay.io/app-sre/assisted-image-service:1f34613
11:30:41 + IMAGE=quay.io/app-sre/assisted-image-service:1f34613
11:30:41 + make build
11:30:41 podman build -f Dockerfile.image-service . -t quay.io/app-sre/assisted-image-service:1f34613
11:30:41 make: podman: Command not found
11:30:41 …
```
=> Use docker for build script instead of podman

README.md, internal/handlers/images.go, internal/handlers/images_test.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go, pkg/imagestore/mock_imagestore.go
This commit moves us from the map versions format inspired by the old
assisted-service `OPENSHIFT_VERSIONS` map to the new format for
`RHCOS_VERSIONS`. The main difference is using an array instead of a
map.
This also adds a cpu_architecture field to each default version entry.
A follow-up PR will add a parameter to the API to specify architecture.
Ran the service locally and tested generating both full and minimal isos for an infra-env in integration.
Both images registered successfully.
/cc @djzager 
Related assisted-service PRs:
https://github.com/openshift/assisted-service/pull/2369
https://github.com/openshift/assisted-service/pull/2454
JIRA:
https://issues.redhat.com/browse/MGMT-7453
=> Use array format for versions and add image arch support

README.md, internal/handlers/images.go, internal/handlers/images_test.go, main.go
The assisted-service may likely be using self-signed certificates. This
change makes it possible to start the imagehandler with a cabundle to
make trust between the image-service and assisted-service possible.
Additionally, we break up the handling of `err != nil` to ensure we
don't panic because response != 2xx but err was nil.
dev-scripts environment
/cc @carbonin 
/cc @
https://github.com/openshift/assisted-service/pull/2480
=> feat: support self-signed certificates on assisted-service

README.md, internal/handlers/images_test.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
When constructing the download URL from assisted-service it will be
better to use the image type directly from that API rather than
translating it.
Specifically changes "full" to "full-iso" and "minimal" to "minimal-iso"
Unit tests cover this rather well.
/cc @djzager 
/cc @flaper87 
Related to https://issues.redhat.com/browse/MGMT-7258
=> Align type values with those from assisted-service

pkg/isoeditor/isoeditor_suite_test.go, pkg/isoeditor/isoutil.go, pkg/isoeditor/isoutil_test.go
As the aarch64 rhcos image[*] contains a single boot image (efiboot.img),
added proper support to isoutil for creating an ISO with only that boot platform.
This should facilitate the creation of a minimal ISO template for arm64 CPU architecture.
Note: same as done in assisted-service - https://github.com/openshift/assisted-service/pull/2563
[*] https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/pre-release/4.9.0-fc.1/rhcos-4.9.0-fc.1-aarch64-live.aarch64.iso
Tested same change in assisted-service.
/cc @carbonin
=> MGMT-7754: Support iso creation with EFI boot only

Dockerfile.image-service
The original plan was to move all images to ubi8. This is not possible due to the lack
of some packages that are needed for other projects. We are now going to switch all images
to stream8 with the hope that the consistency accross repos will prevent (or help) with
debugging current/future issues in CI.
The goal is to keep component's builds as consistent as possible in the channels we are
releasing them on
Signed-off-by: Flavio Percoco <flavio@redhat.com>
It wasn't! Relying on CI for this 
/cc @carbonin 
/cc @djzager
=> MGMT-7762: Switch to stream8

README.md, internal/handlers/images.go, internal/handlers/images_test.go, main.go
When testing large numbers of simultaneous downloads (~1000)
some of the requests failed due to hitting an open file limit.
This commit adds an environment variable that allows us to cap the
number of downloads in progress.
Ran the image service locally against a "no-op" assisted service that just returned some content immediately to any request.
I issued 1000 simultaneous requests to download images from the assisted service and ran into issues with local file limits like this:
`{"file":"/home/ncarboni/Source/assisted-image-service/internal/handlers/images.go:138","func":"github.com/openshift/assisted-image-service/internal/handlers.(*ImageHandler).ServeHTTP","level":"error","msg":"Error creating image stream: failed to create overwrite reader for ramdisk: Could not open device …
=> Limit requests in flight for image downloads

internal/handlers/images.go, internal/handlers/images_test.go, main.go
After this change requests to assisted-service will be
canceled if/when the request to the image service is canceled.
This will ensure that requests that the client doesn't care about won't
run nmstatectl processes on assisted-service.
This also uses the `golang.org` semaphore package rather than a custom implementation.
An image with this change was deployed to OpenShift alongside assisted service where I confirmed that canceling a download request on the client killed the running nmstatectl processes in the assisted service pod.
/cc @djzager 
https://bugzilla.redhat.com/show_bug.cgi?id=2010819
=> Bug 2010819: Use the request context when making requests to assisted-service

internal/handlers/images.go, internal/handlers/images_test.go, pkg/isoeditor/ignition.go, pkg/isoeditor/ignition_test.go, pkg/isoeditor/stream.go, pkg/isoeditor/stream_test.go
All users of NewRHCOSStreamReader will need to convert the image data to
a gzip-compressed CPIO archive, so move this code out of the internal
package. To ensure future compatibility (e.g. if more than one file had
to be inserted in the archive), implement this code in a new
IgnitionContent type.
Unit tests
/cc @carbonin 
https://github.com/openshift/image-customization-controller/pull/4#discussion_r726219950
=> Make Ignition archiving code public

README.md, integration_test/images_test.go, internal/handlers/images.go, internal/handlers/images_test.go, main.go
This commit changes how the image service handles authentication
parameters. Previously an environment variable (`REQUEST_AUTH_TYPE`) was
used to change how the image service would treat the `api_key` query
parameter.
This didn't end up working out as we want to use a different query
parameter name for different auth types and the effect of changing
`REQUEST_AUTH_TYPE` was unclear.
This commit removes `REQUEST_AUTH_TYPE` and implements separate handling
for each authentication strategy. This should clear up how what is passed
to the image service gets used in calls to assisted service.
Specifically the mappings are now:
| image service auth            | assisted service auth     |
|-------------------------------|---------------------------|
| `api_key` query parameter     | `api_key` …
=> MGMT-7897: Rework authentication handling to support image_token

deploy/template.yaml
This will be used to deploy the image service to the console.redhat.com
SaaS service. IMAGE_TAG is dynamically filled based on deployment
configuration.
Deployed this template along with assisted-service on a crc cluster and successfully configured assisted-service to set infra-env download urls to the deployed image service.
Created an infra-env and successfully downloaded the image through a route I created pointing to image service service.
/cc @osherdp 
/cc @filanov 
/cc @rporres 
https://issues.redhat.com/browse/MGMT-7716
=> MGMT-7716: Add a template to deploy to console.redhat.com

README.md, internal/handlers/images_test.go, internal/handlers/liveness.go, internal/handlers/readiness.go, main.go
Clone of Bug 2012796
- Add new endpoint `live`, that always respond 200.
- Change endpoint `health` to respond 503 until the `Populate` is done.
/cc @carbonin 
/cc @
Original PR:
https://github.com/openshift/assisted-image-service/pull/36
=> Bug 2023616: Add liveness endpoint

pkg/isoeditor/initramfs.go, pkg/isoeditor/initramfs_test.go, pkg/overlay/overlay.go, pkg/overlay/overlay_test.go
In addition to the existing `NewRHCOSStreamReader()` function to generate a streamable customised ISO file, add a new `NewInitRamFSStreamReader()` function to do equivalent customisation of an initramfs file for the purposes of PXE booting.
The [initramfs format](https://www.kernel.org/doc/html/latest/driver-api/early-userspace/buffer-format.html) consists of a sequence of gzipped cpio archives (each archive is gzipped separately), so the customisation can be performed by simply appending a new archive at the end of the stream. The archive itself is identical to the one used to customise the ISO.
=> Add the ability to customise PXE files

internal/handlers/images.go, internal/handlers/images_test.go, pkg/isoeditor/initramfs.go, pkg/isoeditor/stream.go, pkg/overlay/overlay.go
It's possible that this was being cleaned up automagically so that we don't leak buffers/file descriptors/something else, but better to explicitly close the base file after the request is completed.
=> Close the ISO file after serving a request

go.mod, go.sum, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
For avoiding a corrupt base iso in persistent storage, use google/renameio package that ensures atomic file write.
I.e. if a download is interrupt, no leftover should remain in storage.
Consequently, the service could recover once rescheduled by redownloading the missing image.
Tested manually and using unit tests.
/cc @carbonin 
/cc @filanov 
/cc @rollandf
=> MGMT-8306: Use renameio in downloadURLToFile

deploy/template-monitoring.yaml, deploy/template.yaml
This commit adds an additional template which describes the
ServiceMonitor required to collect metrics from the image service.
Additionally it makes some minor changes to the app template to make the
object references easier.
`oc process --local -f deploy/template-monitoring.yaml -pNAMESPACE=assisted-installer-stage`
:point_up: succeeds
We'll have to wait for this to deploy to see if metrics are gathered properly.
/cc @osherdp 
/cc @filanov 
https://issues.redhat.com/browse/MGMT-7715
=> Add monitoring template for gathering metrics

internal/handlers/images.go, internal/handlers/images_test.go
This will allow clients looking for this header to automatically set the
downloaded file name to something that makes sense.
Ran the image service from this branch against assisted service in the stage cloud environment and downloaded an iso with the following `curl` command:
`curl -k -v -OJ -H "Authorization: Bearer $(ocm token)" "https://localhost:8080/images/d77694d1-0ee4-4812-a60b-7ac02d41c6ad?type=minimal-iso&version=4.8&arch=x86_64"`
This resulted in a file named `d77694d1-0ee4-4812-a60b-7ac02d41c6ad-discovery.iso` written in the working directory.
/cc @rollandf 
https://bugzilla.redhat.com/show_bug.cgi?id=2015961
=> Set the Content-Disposition header

README.md, go.mod, go.sum, internal/handlers/middleware.go, internal/handlers/middleware_test.go, main.go
This commit adds middleware to handle adding CORS headers to API
responses. The new env var `ALLOWED_DOMAINS` is a comma-separated list
of domains which should be allowed to access content from this API.
The CORS middleware is only used when a value is set for
`ALLOWED_DOMAINS`.
Started the service locally with and without the new env var.
Observed the correct handling when an `Origin` request header was passed with a matching domain and a non-matching one.
/cc @tsorya 
https://issues.redhat.com/browse/MGMT-8688
=> Handle CORS headers properly

build_deploy.sh
Seems like we might fail pushing images to the app-sre namespace, depending on scheduling of cleanup jobs occurring from time to time for Jenkins agents.
This has led to the idea that it might be beneficial to build the image from scratch (including intermediate layers that should usually be cached). It's also a good idea to always build the whole image, ignoring stuff that might was buildable before but not now.
Sadly we don't have a way to trigger cleanup or simulate it in a good way. We'll have to monitor it from time to time.
If needed, slack link includes some more suggestions based on past experience.
/cc @carbonin 
/cc @filanov 
https://ci.ext.devshift.net/job/openshift-assisted-image-service-gh-build-main/34/console
https://coreos.slack.com/archives/CCRND57FW/p1642341209291500
=> MGMT-8927: build image from scratch to handle possible cleanups

integration_test/images_test.go, pkg/isoeditor/rhcos.go, pkg/isoeditor/rhcos_test.go
Discovery ISO might be FCOS based, so `grub.cfg` needs to be looked up in a different path. This PR checks which of two paths - RHCOS and FCOS - is available and uses it throughout the function
Tested AI flow with FCOS 34 as a base for ISO image
/cc @carbonin
/cc @rollandf
=> isoeditor: support editing FCOS grub.cfg

integration_test/images_test.go, main.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
[Bugzilla 2034686](https://bugzilla.redhat.com/show_bug.cgi?id=2034686): Allow for disabling TLS verification for fetching ISOs
Manually tested by creating an nginx server secured with a self-signed certificate in the assisted-image-service pod, hosting a file, and updating the assisted-service-config configmap's OS_IMAGES to point to the file url.
/cc @carbonin 
/cc @
=> Bug 2034686: Allow for disabling TLS verification for fetching ISOs

main.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
[Bug 2046521](https://bugzilla.redhat.com/show_bug.cgi?id=2046521): Allow disabling TLS verification
Cherry-picked from e61d9e7.
Original PR: https://github.com/openshift/assisted-image-service/pull/53
Manual, see original [PR](https://github.com/openshift/assisted-image-service/pull/53)
/cc @carbonin 
/cc @
- https://github.com/openshift/assisted-image-service/pull/53
=> Bug 2046521: Allow for disabling TLS verification for fetching ISOs.

integration_test/images_test.go
The images are currently not published in latest because of an
issue in the release process and makes our unit tests fail.
This is a workaround until the release process is fixed.
=> NO-ISSUE: Update RHCOS pre-release x86_64 image URL

pkg/imagestore/imagestore.go
http.DefaultTransport has some useful properties set that are not
present in a zero-value transport struct.
Specifically it sets up a function for fetching proxy environment
variables.
When we moved from using the default transport to creating our own to
solve https://bugzilla.redhat.com/show_bug.cgi?id=2034686 we also
removed the proxy environment variable handling as a side-effect.
This was verified to fix the proxy issue in @chadcrum 's test environment.
https://bugzilla.redhat.com/show_bug.cgi?id=2038903
=> Use fields from http.DefaultTransport in imagestore

pkg/overlay/overlay.go, pkg/overlay/overlay_test.go
It's valid for a reader to return EOF at the same time as the last
bytes. If we have such a reader as the base for an overlay we return EOF
when the base reader returns EOF even if we haven't printed the overlay
yet.
This is specifically a problem for the append reader when we're always
getting to the end of the base before starting to read the overlay.
Unit and integration tests cover this
/cc @zaneb 
/cc @filanov 
https://issues.redhat.com/browse/MGMT-9333
=> Fix overlay reader for base readers that return EOF early

README.md, integration_test/images_test.go, internal/handlers/boot_artifacts.go, internal/handlers/boot_artifacts_test.go, internal/handlers/handlers_suite_test.go, internal/handlers/images.go, internal/handlers/images_test.go, main.go, pkg/isoeditor/isoutil.go
This PR adds a new endpoint to the image service
which will serve the rootfs or the kernel directly
from an ISO.
The new endpoint is of the form:
```
/boot-artifacts/{artifact-name}?{params}
```
For example:
```
/boot-artifacts/rootfs?version=4.9&arch=x86_64
/boot-artifacts/kernel?version=4.10&arch=arm64
```
Ran the image service locally and downloaded the rootfs and kernel using the new endpoints.
Ensured that they matched exactly the same files extracted from the iso using the `iso-read` command line tool.
/cc @mhrivnak 
Enhancement doc: https://github.com/openshift/assisted-service/pull/3389
JIRA: https://issues.redhat.com/browse/MGMT-9332
=> MGMT-9332: Add endpoint for rootfs and kernel

pkg/imagestore/imagestore.go, pkg/isoeditor/rhcos.go
In order to reduce the temporary space used to build the minimal ISO image, we don't want to extract all the images in parallel, then remove the `rootfs` and build it again. Instead, we'll download all the required images in parallel, as it is right now, and the build the images sequentially one by one, to reduce the space consumption. 
``` 
All in parallel:
Download ISO 1 ------- Download ISO 2 ------ Download ISO 3
|                   |                       |
Build min ISO 1 --------- Build min ISO 2 ------ Build min ISO 3
```
```
Download in parallel: 
Download ISO 1 ------- Download ISO 2 ------ Download ISO 3
Build sequentially: 
- Build min 1
- Build min 2
- Build min 3
```
Monitoring the folder where the images are extracted and checking that there is no more than 1 extracted …
=> MGMT-9019: Download full ISO in parallel, but build the mionimal ISO sequentially

internal/handlers/handlers_suite_test.go, internal/handlers/readiness.go, internal/handlers/readiness_test.go, main.go
This commit extends the readiness handler to provide a middleware that
will return 503s until we mark the handler ready. It will then call the
underlying handler.
This new middleware is applied to both the images and boot-artifacts
endpoints so it's more clear to a user that the failure it temporary
rather than some issue with the deployment or configuration.
Deployed the service locally and tested responses from both the images and boot-artifacts endpoints before and after the template images were finished downloading.
/cc @filanov 
https://issues.redhat.com/browse/MGMT-9395
=> Return a 503 from images and boot-artifacts before downloads finish

integration_test/images_test.go, internal/handlers/assisted_service_client.go, internal/handlers/initrd_test.go, internal/handlers/iso_test.go, main.go
This PR ensures that we use `log.Fatalf` only in the `main` function and not from internal or other package functions.
/cc @carbonin
=> MGMT-9538: Only log.Fatal from main in the image service

internal/servers/servers.go, internal/servers/servers_test.go, main.go
IPXE flow requires artifacts to be available via HTTP. This change would ensure that if `LISTEN_HTTP_PORT` env var is set and HTTPS cert/key are set, the same endpoints are exposed on plain HTTP port as well
TODO:
local deployment
/cc @carbonin 
/cc @filanov
=> Bug 2078531: add an option expose all endpoints on plain HTTP port

hack/setup_env.sh
`go get` mutates go.mod/go.sum, so we should use "go install" to install additional tools.
This also unsets `GOFLAGS` when installing `goimports`/`mockgen` to avoid failing on CI as it has `-mod=vendor` set there by defaults
=> hack: use `go install` to install goimports and mockgen

deploy/template.yaml, pkg/imagestore/imagestore.go
This change should mainly affect integration env, having nightly-built images of OCP 4.11 (no fc/rc release has been promoted to date).
I also took the liberty to add 4.10 ARM image which seems missing.
``oc process --local -f deploy/template.yaml -pIMAGE_TAG=latest`` seems to work.
For some reason I couldn't make ``RHCOS_VERSIONS`` have a minimal value (without line-breaks), even when using ``value: <-`` but I think it's not a big issue.
/cc @carbonin 
[MGMT-10623](https://issues.redhat.com//browse/MGMT-10623)
=> MGMT-10623: Add OCP 4.11 nightly images

README.md, integration_test/images_test.go, main.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
When creating a minimal ISO template the rootfsURL is injected to grub config files.
For each OS image metadata (OS_IMAGES) the rootfs_url is available as an external URL to the img file.
This URL is currently used on imagestore -> Populate.
This change is removing the requirement to specify an external rootfs URL for each image, instead, we're now using the
/boot-artifacts/rootfs API. I.e. a URL as follows is generated when creating the minimal ISO and injected to the grub configs:
http://`<image-service-base-url>`/boot-artifacts/rootfs?arch=x86_64&version=4.10
Hence, when deploying the image service, IMAGE_SERVICE_BASE_URL env var should be now specified.
Note: the previous behaviour of using the rootfs_url from OS_IMAGES is kept as a fallback for now. Can be removed later on once …
=> MGMT-10751: use boot-artifacts API as rootfs URL

Dockerfile.image-service, Dockerfile.image-service-build, go.mod
Updated golang in:
* go.mod: go 1.16 -> go 1.17
* bump openshift/release to golang-1.17 in Dockerfile
Address issues discovered in:
- https://github.com/stolostron/backlog/issues/23440
- https://github.com/stolostron/backlog/issues/23369
- https://github.com/stolostron/backlog/issues/23297
Invoked tests locally and waiting for CI to do a full run
/cc @carbonin
=> NO-ISSUE: bump golang to 1.17

deploy/template.yaml, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
* As the service CRD for SaaS deployment is in the template, added IMAGE_SERVICE_HOST env var.
* As we can't fetch the external url of the image-service, Set IMAGE_SERVICE_HOST by IMAGE_SERVICE_BASE_URL env var.
* In buildRootfsURL, added support for a host string that contains scheme and path.
Added relevant unit-tests.
/cc @carbonin
=> MGMT-11048: add image_service_host var to template

deploy/template.yaml, pkg/imagestore/imagestore.go
There's currently no usage of OCP 4.6 in SaaS prod, so we can clean up this version from all our environments.
No tests needed
/cc @gamli75 
/cc @danielerez
=> Remove OCP 4.6 from integration environment

deploy/template.yaml, pkg/imagestore/imagestore.go
It is unused on prod SaaS, so there's no need for us to download a redundant ISO image in our tests.
No test needed
https://issues.redhat.com/browse/MGMT-11618
=> MGMT-11618: remove OCP 4.7 from integration env

pkg/servers/servers.go, pkg/servers/servers_test.go
When running unit tests locally, I ran into a couple of issues
1: The tests would have frequent connection failures when trying to create http servers on various ports, this felt like a bug, but would not consistently happen for all users.
2: The unit tests would take a long time to "clean up" adding a lot of uneccesary overhead to tests.
This commit makes sure that when we launch a HTTP or HTTPS server that we wait a reasonable amount of time for them to come online before exiting the non-blocking ListenAndServe() method.
We also added a "Fast shutdown" mode to the HTTP and HTTPS servers where the connection will be closed instead of shut down. This is exclusively for use in testing environments and should not be used in production.
By running the unit tests
/cc @carbonin 
/cc @nmagnezi
=> NO-ISSUE: Performance enhancements for unit tests

deploy/template.yaml
It looks like this hasn't been updated in a while and it's missing 4.12 leading to 400 errors when downloading images.
This also updates the whole map to match the assisted-service repo
As a follow up we should also update the other image lists in this repo, but let's just get integration working first.
Tested with `oc process -f deploy/template.yaml --local`.
Template renders fine.
/cc @osherdp 
/cc @eliorerz
=> Update os images in openshift deploy for integration

integration_test/images_test.go, internal/handlers/assisted_service_client.go, internal/handlers/initrd.go, internal/handlers/iso.go, internal/handlers/iso_test.go
This will make a request to the assisted-service, passing the value of the request parameter "imageType"
When the PR https://github.com/openshift/assisted-service/pull/4309 is merged then the assisted service will respond by
including static networking config in the discovery ignition when a minimal iso is requested.
The static networking config will not be included in the ignition if a full iso is requested.
This code is covered by modification of unit tests to cover the functionality.
/cc @carbonin 
/cc @nmagnezi
=> MGMT-11442: Fetch discovery ignition with static networking if minimal iso requested.

integration_test/images_test.go, internal/handlers/assisted_service_client.go, internal/handlers/iso.go, internal/handlers/iso_test.go, pkg/isoeditor/isoeditor_suite_test.go, pkg/isoeditor/isoutil.go, pkg/isoeditor/kargs.go, pkg/isoeditor/kargs_test.go, pkg/isoeditor/stream.go, pkg/isoeditor/stream_test.go
When streaming the discovery ISO file, the kernel arguments are included as part of some files: grub.cfg and isolinux.cfg
Each of these files contains an area where the kernel arguments can be embedded. This are can be identified by the regex "(\n#+) COREOS_KARG_EMBED_AREA". The arguments should overwrite this are from the beginning and should not pass the last # (hash sign). To do that, an overlay was created.
In new Openshift versions, there is a file that contains the file names, while in old versions the file does not exist. If the file exists, the files to embed the kernel arguments are taken from this config file. Otherwise, the default files [/EFI/redhat/grub.cfg, /isolinux/isolinux.cfg] are used.
/cc @carbonin 
/cc @filanov
=> MGMT-12054: Support discovery kernel arguments for full-iso and minimal-iso

Dockerfile.image-service
The latest image includes the updated openssl-libs package:
```
$ podman run --pull=always -it --rm quay.io/centos/centos:stream8 rpm -q --changelog openssl-libs 2>/dev/null | grep -B 1 CVE-2022-0778
* Wed Mar 23 2022 Clemens Lang <cllang@redhat.com> - 1:1.1.1k-6
- Fixes CVE-2022-0778 openssl: Infinite loop in BN_mod_sqrt() reachable when parsing certificates
```
`make build`
/cc @carbonin 
https://github.com/openshift/assisted-image-service/pull/69
=> removes openssl-libs update for CVE-2022-0778

Dockerfile.image-service-build, hack/setup_env.sh
Due to several CVE bugs we need to update golang version to >= v1.18.1.
https://bugzilla.redhat.com/show_bug.cgi?id=2077688
https://bugzilla.redhat.com/show_bug.cgi?id=2077689
This PR updates golang version to v1.18.1 and golangci to v1.46.0.
=> OCPBUGSM-46219: OCPBUGSM-46220: Update golang version to 1.18.1.

go.mod, go.sum, integration_test/images_test.go, pkg/isoeditor/isoutil.go, pkg/isoeditor/isoutil_test.go, pkg/isoeditor/stream_test.go
This includes a fix for a panic when we attempt to open a fedora server ISO.
```
$ export OS_IMAGES='[{"openshift_version": "4.8","cpu_architecture": "x86_64","url": "https://download.fedoraproject.org/pub/fedora/linux/releases/37/Server/x86_64/iso/Fedora-Server-dvd-x86_64-37-1.7.iso","version": "48.84.202109241901-0"}]'
$ IMAGE=quay.io/carbonin/assisted-image-service:latest make build run
```
Before the update this resulted in:
```
{"file":"/go/src/github.com/openshift/origin/pkg/servers/servers.go:94","func":"github.com/openshift/assisted-image-service/pkg/servers.(*ServerInfo).httpsListen","level":"info","msg":"Starting https handler on :8080...","time":"2022-12-01T13:55:56Z"}
{"file":"/go/src/github.com/openshift/origin/pkg/imagestore/imagestore.go:277","func":"github.com/openshift/ass …
```
=> Update go-diskfs to latest

OWNERS_ALIASES
Since there are (currently) no label restrictions on attached Jira bugs, we don't have a good way to enforce people are only merging bug-fixes / security-patches.
Setting a smaller approvers list can help us enforce this kind of restriction (list might change later on, if needed)
No tests required.
/cc @filanov @gamli75 @romfreiman @carbonin 
https://issues.redhat.com/browse/MGMT-12840
=> MGMT-12840: set restricted list of approvers for 2.7

internal/handlers/assisted_service_client.go, internal/handlers/assisted_service_client_test.go
… 
Presently, if the user does not provide ASSISTED_SERVICE_HOST before running the service, there will be a nil dereference error. This was due to the absence of ASSISTED_SERVICE_HOST not being correctly validated. This PR changes that by introducing a clear validation around this.
I introduced a unit test and also performed a manual check.
This test was tested by using the reproduction steps in https://issues.redhat.com/browse/MGMT-12548 , namely
1. clone the repo
2. run `make run`
3. issue the following request 
curl -i -k "https://127.0.0.1:8080/images/d4af4288-65af-4507-995e-43a9a96f857a?arch=x86_64&image_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk1NzEzOTIsInN1YiI6ImQ0YWY0Mjg4LTY1YWYtNDUwNy05OTVlLTQzYTlhOTZmODU3YSJ9.j9HQZnLVIcJkA5Hea1HCG1qkqcMSLQhaS3nDZkq8blQ&type=minim …
=> MGMT-12548: Return a more graceful error if ASSISTED_SERVICE_HOST not set

pkg/isoeditor/initramfs.go
Because `NewInitRamFSStreamReader()` takes a filename as an input, this requires us to copy the initramfs to a temporary file if we are retrieving it from inside an ISO.
Add a separate `NewInitRamFSStreamReaderFromISO()` function that takes the filename of the ISO instead, so that we can output an initramfs with Ignition from an ISO input without temporary files.
=> AGENT-438: Allow initramfs to be read directly from ISO

integration_test/images_test.go, internal/handlers/iso.go, internal/handlers/iso_test.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go, pkg/isoeditor/mock_editor.go, pkg/isoeditor/rhcos.go, pkg/isoeditor/rhcos_test.go
@carbonin and I worked on this together to enable ppc64le (Power) and s390x (Z) architectures in the assisted-image-service. This is related to the [PR](https://github.com/openshift/assisted-service/pull/4796) in the assisted-service to enable these architectures related to this multi-arch [epic](https://issues.redhat.com/browse/MULTIARCH-2889).
We're working around some limitations with s390x as it doesn't use grub, which also means we can't extract a minimal iso from it. The CoreOS team is [working on](https://issues.redhat.com/browse/COS-1924) enabling minimal iso extraction for s390x at the moment. If/when they get it working we can revisit some of these changes, but for now we're just going to skip minimal iso extraction for s390x.
Neither architecture has an isolinux.cfg file, so we …
=> Support ppc64le and s390x

deploy/template.yaml
Update 4.12 images to the GA ones 
/cc @gamli75 
/cc @osherdp
=> MGMT-12975: Update 4.12 release image to use GA version

deploy/template.yaml
This brings the ISO urls up to date with the data in the assisted-service repo.
This will only affect the integration SaaS environment.
`oc process -f template.yaml --local=true -pIMAGE_SERVICE_BASE_URL=image-service.example.com -pIMAGE_TAG=latest` 
succeeds
/cc @osherdp 
/cc @eliorerz
=> Update base ISO images to assisted-service data

deploy/template.yaml
Adds 4.12 ppc64le and s390x ISOs for 4.13 dev preview testing, in parity with #111 and #115.
Did not test, am having some troubles with getting my assisted-service running.
Ok to let CI test?
/cc @eliorerz 
/cc @carbonin
/cc @osherdp
/cc @gamli75 
#111 
#115
[PR](https://github.com/openshift/assisted-service/pull/5005) in assisted-service
=> Add support for 4.13 dev preview images

integration_test/images_test.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go, pkg/isoeditor/kargs_test.go, pkg/isoeditor/rhcos.go
Allow images with "scos-" volume ID
Cherrypick of https://github.com/openshift/assisted-image-service/pull/114 for ACM 2.7
=> MGMT-13935: validateISOID: allow SCOS images

pkg/isoeditor/rhcos.go
Update available grub paths to allow CentOS images, so that CentOS  Stream test images could be parsed correctly
Partial cherrypick of https://github.com/openshift/assisted-image-service/pull/117 on release-ocm-2.6
/cc @carbonin 
/cc @filanov
=> OCPBUGS-10948: isoeditor: allow centos images

Makefile, README.md, main.go
The log level can now be set via environment variable, enabling developers and operators to see debug messages.
Hand testing and the existing suite of integration tests.
/cc @carbonin
=> adds ability to set the log level

README.md, go.mod, go.sum, integration_test/images_test.go, internal/handlers/assisted_service_client.go, internal/handlers/images.go, internal/handlers/images_test.go, internal/handlers/initrd.go, internal/handlers/initrd_test.go, internal/handlers/iso.go, internal/handlers/iso_test.go, internal/handlers/long.go, internal/handlers/middleware.go, internal/handlers/short.go, internal/handlers/short_test.go, main.go
Implements the [Short Image URL
enhancement](https://github.com/openshift/assisted-service/blob/master/docs/enhancements/short-url-enhancement.md).
Quoting the enhancement summary: "The assisted-image-service should be enhanced to serve discovery ISOs from URLs that are less than 255 characters and don't have query parameters. This will enable servers from multiple vendors to directly boot from an assisted-image-service URL using the baseboard management controller."
by hand and with new automated tests
/assign @carbonin
=> MGMT-12743: adds support for shorter URLs

deploy/template.yaml
This clones the entries for OCP 4.13 images to OCP 4.14, as there are no officially released 4.14 images.
The actual effect of this PR is only for the integration system which uses the default value of ``OS_IMAGES`` (test-infra automation uses the configuration in ``assisted-service`` repo).
I need to check if we're within the PVC capacity. Other than that, I'll verify installation works with those images locally.
/hold
/cc @carbonin 
/cc @gamli75 
https://issues.redhat.com/browse/MGMT-14370
=> MGMT-14370: add initial live-iso images for 4.14

.ci-operator.yaml
This enables building the build-root image from the HEAD commit instead of base commit, meaning PRs changing Dockerfiles are tested including their Dockerfile changes.
This is a preliminary stage for moving to stream9 U/S, as it makes testing much easier.
This can only be tested in the followup PR to ``openshift/release``.
/cc @eliorerz 
/cc @gamli75 
https://issues.redhat.com/browse/MGMT-15822
=> MGMT-15822: use Dockerfiles of head commit

Dockerfile.image-service
Now that D/S building system fully supports RHEL-9 base images (and allows easy installation of nmstate and other libs that were previously unsupported) we can move U/S to stream9 and D/S to ubi9-minimal.
It doesn't seem possible to easily use ubi9-minimal U/S for the assisted-service, because installation of nmstate packages either requires entitlements running on a RHEL node, or alternatively an access to RedHat's internal network (which can be a major problem for U/S development). For a better consistency we're sticking with the same for the agent, installer, etc.
CI will do the tests.
TBD
https://issues.redhat.com/browse/MGMT-15822
=> MGMT-15822: change base image to stream9

pkg/isoeditor/isoeditor_suite_test.go, pkg/isoeditor/stream.go, pkg/isoeditor/stream_test.go
Note that this is mostly a copy of #139. The differences is that there are no changes in the integration tests, and a new unit test was added to verify the use of `igninfo.json` in S390 ISOs. Below is the description originally written by @carbonin:
> If the ignition info file (/coreos/igninfo.json) is present in the ISO
> use it to determine where the ignition content should be embedded
> instead of assuming it should always go in "/images/ignition.img"
>
> If an error is encountered when reading the ignition info, fall back to
> the previous ignition path. This allows the image service to seamlessly
> support older versions without having to explicitly include logic about
> which version is being used in every call.
Added a unit test that creates a ISO that simulates the `igninfo.json` …
=> MGMT-13692: Use ignition info

deploy/template.yaml
This clones the entries for OCP 4.14 images to OCP 4.15, as there are no officially released 4.15 images.
The actual effect of this PR is only for the integration system which uses the default value of OS_IMAGES (test-infra automation uses the configuration in assisted-service repo).
/cc @rccrdpccl
=> MGMT-16077: Add release and OS images for OCP 4.15

pkg/isoeditor/isoeditor_suite_test.go, pkg/isoeditor/stream.go, pkg/isoeditor/stream_test.go
This is a backport of [MGMT-13692](https://issues.redhat.com/browse/MGMT-13692) and #156 for ACM 2.9.
Note that this is mostly a copy of #139. The differences is that there are no changes in the integration tests, and a new unit test was added to verify the use of `igninfo.json` in S390 ISOs. Below is the description originally written by @carbonin:
> If the ignition info file (/coreos/igninfo.json) is present in the ISO
> use it to determine where the ignition content should be embedded
> instead of assuming it should always go in "/images/ignition.img"
>
> If an error is encountered when reading the ignition info, fall back to
> the previous ignition path. This allows the image service to seamlessly
> support older versions without having to explicitly include logic about
> which …
=> MGMT-16239: Use ignition info - ACM 2.9

integration_test/images_test.go, main.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
[MGMT-16507](https://issues.redhat.com//browse/MGMT-16507): Enable image service to use additional ca certificates
The infrastructure operator will make available a file at ASSISTED_SERVICE_API_TRUSTED_CA_FILE
This file will contain certificates that are to be used for certificate authority during image fetch
The purpose of this PR is to use those certificates for the fetching of images if they have been set up.
Additionally, we needed to make the  the purpose of HTTPS_CA_FILE clearer, so we added a new variable OS_IMAGE_DOWNLOAD_TRUSTED_CA_FILE
The value of OS_IMAGE_DOWNLOAD_TRUSTED_CA_FILE will default to the value held in HTTPS_CA_FILE unless overridden
The idea is to retire HTTPS_CA_FILE as it is not very clear what it's for.
OSImageDownloadTrustedCAFile is a path to a CA file that …
=> MGMT-16507: Enable image service to use additional ca certificates

integration_test/images_test.go, main.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
This PR provides the ability to add custom query parameters and headers to every http request made while downloading OS images.
Two environment variables are to be provided `OS_IMAGES_HTTP_REQUEST_QUERY_PARAMS` and `OS_IMAGES_HTTP_REQUEST_HEADERS` These variables are JSON representations of `map[string]string` where the key is the parameter (or header) name and the value is the parameter (or header) value.
Once provided, these values will be used in the HTTP request headers and the HTTP query parameters of any request made during the download of OS images.
This code includes tests to ensure that the functionality works as intended. A manual test will also be performed in podman to ensure the behavior is as expected
/cc @carbonin 
/cc @omertuc 
This is part of the Epic …
=> MGMT-16629: Use custom query params and headers for OS image downloads

pkg/imagestore/imagestore.go
When using a custom CA for OS image download, it was discovered that the default CA's were not being used.
This is because of how the field `RootCAs` in `TLSClientConfig` is handled in the http client;
if `RootCAs` in `TLSClientConfig` is nil then the default CA's are used, however if the value of `RootCAs` is not nil then the default CA's are overwritten.
The solution is to use x509.SystemCertPool() instead of creating a new one.
This PR ensures that our custom CA is appended to to the default CA's rather than being treated as their replacement.
Manually tested by installation of the infrastructure operator, setting OSImageCACertRef to a valid ConfigMap containing a valid CA and using a set of OS images in the AgentServiceConfig from a mixture of sources so that some will require the …
=> MGMT-16952: Make sure default CA's are preserved when using custom CA

main.go
We recently introduced a feature that allows the passing of headers and query parameters for a request for OS images. The environment variable names we used in the image service were not consistent with the Volume bindings in the statefulset generated by the infrastructure operator.
This PR fixes that by applying the correct bindings.
This code as been tested "end to end" in a QE environment.
/cc @carbonin 
- x] Relevant issues have been associated
=> MGMT-17006: Fix incorrect env var names used for osImageDownloadHeadersMap and osImageDownloadQueryParamsMap

internal/handlers/initrd.go, pkg/isoeditor/initramfs.go
Refactor the assisted image service's handler for the initramfs to make use of the identical code in the isoeditor library's `NewInitRamFSStreamReaderFromISO()` function.
=> NO-ISSUE: Refactor to use isoeditor library internally for initrd

pkg/isoeditor/ignition_image.go, pkg/isoeditor/ignition_image_test.go, pkg/isoeditor/stream.go
Add a `NewIgnitionImageReader()` function to the `isoeditor` package that will allow the agent installer to generate the correct data for an ignition image:
- without knowing the filename (which is different on different architectures)
- even if there is other data apart from the embed area in the image (which happens on s390)
- even if the ignition data is larger than the embed area (as long as it is safe to do so)
- passing the type-safe IgnitionContent type
- reusing the same code that `NewRHCOSStreamReader()` uses to find the embed area
The function returns the filename within the ISO and a Reader for the data. This can be copied over the corresponding file in the directory unpacked by `Extract()`.
=> MULTIARCH-2678, OCPBUGS-14478: Add a NewIgnitionImageReader() function

pkg/isoeditor/ignition_image.go, pkg/isoeditor/isolate_file.go, pkg/isoeditor/kargs.go
Add a function analagous to the `NewIgnitionImageReader()` function, but for kargs. Given a path to an ISO and some kargs to append, it returns a list of files and the new contents that they need to be overwritten with. This will allow the agent-based installer to stop duplicating the code to append kargs in the ISO.
=> AGENT-890: Add NewKargsReader() function

pkg/isoeditor/isoutil.go
The isoeditor package uses the [diskfs.GetFileSystem()](https://github.com/diskfs/go-diskfs/blob/7e522084e08e87ebea3c79876164b61d39e1f6f4/disk/disk.go#L203) method to access the filesystem of the ISO. Since it's a generic library supporting different types of file systems, the current implementation tries to discover the type of the requested one, checking as first the fat32 fs, loggin a debug error trace in case it isn't.
Agent-based installer uses it (indirectly) in several places when creating the agent ISO image (when the `openshift-installer agent create image` command is executed for example), thus resulting ina very noisy and somehow confusing output, i.e.:
```
level=debug msg=initDisk(): start
level=debug msg=initDisk(): regular file
level=debug msg=trying fat32
level=debug …
```
=> OCPBUGS-33240: Skip fat32 log traces when retrieving the ISO file system in the isoeditor package

README.md, internal/handlers/boot_artifacts.go, internal/handlers/boot_artifacts_test.go, internal/handlers/handlers_suite_test.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go
The ins-file will be taken from iso as rootfs, initrd and kernel.
With the support of LPAR on s390x new boot artefacts / files are needed. On LPAR (Classic and/or DPM) there are following files needed :
rootfs.img
kernel.img
initrd.img
"a ins file"
initrd.addrsize ( load address and size of initrd)
prm file (like the file used for zVM nodes)
This is the first PR to enable the gathering of the ins-file taken from the ISO (generic.ins).
This PR is for Assisted Installer, Agent-based Installer and HCP.
This new hypervisor support will be documented accordingly in the installation docs ([https://issues.redhat.com/browse/MULTIARCH-4514](https://issues.redhat.com/browse/MULTIARCH-4514))
There are set of test cases (unit test).
/assign @carbonin …
=> MULTIARCH-4515: Add support for ins-file as boot artefact.

Dockerfile.image-service
[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
/cc @gamli75 
/cc @eifrach
=> [release-ocm-2.9] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid

Dockerfile.image-service
[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
/cc @gamli75 
/cc @eifrach
=> [release-ocm-2.8] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid

internal/handlers/initrd_addrsize.go, pkg/isoeditor/initrd_addrsize.go, pkg/isoeditor/initrd_addrsize_test.go, pkg/isoeditor/isoeditor_suite_test.go
Refactor code of getting initrd.addrsize file and move the code to isoeditor to support agent-based installer.
This is required that the agend-based installer can use the isoeditor to gather the initrd.addrsize file
Move the calculation code from initrd_addrsize handler to isoeditor (smiliar to initrd)
Running initrd_addsize test suit.
@carbonin 
/cc @
/cc @
See PRs:
https://github.com/openshift/assisted-image-service/pull/207
https://github.com/openshift/assisted-image-service/pull/199
=> MULTIARCH-4515i: provide initrd.addrsize endpoint through isoeditor

Dockerfile.image-service-build, hack/setup_env.sh
Download rpm packages in a different stage at the build of Dockerfile-build as golang image is based on centos 7 which cannot reach its repositories as it is EOL
=> NO-ISSUE: Download rpm packages in a different stage at the build of Dockerfile-build

.ci-operator.yaml
Download rpm packages in a different stage at the build of Dockerfile-build as golang image is based on centos 7 which cannot reach its repositories as it is EOL
=> [release-ocm-2.9] NO-ISSUE: Download rpm packages in a different stage at the build of Dockerfile-build

Dockerfile.image-service
Currently, the image service fails to start using podman with a
permission error:
```
{“file”:“/go/src/github.com/openshift/origin/main.go:132",“func”:“main.main.func1",“level”:“fatal”,“msg”:“Failed to populate image store: failed to download https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.14/4.14.15/rhcos-4.14.15-x86_64-live.x86_64.iso: unable to create a temp file for /data/rhcos-full-iso-4.14-414.92.202402130420-0-x86_64.iso: open /data/.rhcos-full-iso-4.14-414.92.202402130420-0-x86_64.iso271460763: permission denied\n”,“time”:“2024-07-02T15:46:45Z”}
```
This change ensures that `/data` directory is writable for the UID/GID
that will be used to execute the image service executable.
=> NO-ISSUE: Ensure data dir is writable by UID/GID

Dockerfile.image-service-build, Makefile, hack/setup_env.sh
Download rpm packages in a different stage at the build of Dockerfile-build as golang image is based on centos 7 which cannot reach its repositories as it is EOL
=> [release-ocm-2.8] MGMT-18332: Download rpm packages in a different stage at the build of Dockerfile-build

Dockerfile.image-service-build, Makefile, hack/setup_env.sh
Download rpm packages in a different stage at the build of Dockerfile-build as golang image is based on centos 7 which cannot reach its repositories as it is EOL
=> [release-ocm-2.9] MGMT-18332: Download rpm packages in a different stage at the build of Dockerfile-build

Dockerfile.image-service
When deployed on OCP, we need to allow the group "root" to write in
data dir because the UID will be randomly selected.
https://docs.openshift.com/container-platform/4.16/openshift_images/create-images.html#use-uid_create-images
=> NO-ISSUE: Allow goup root to write into data dir

Dockerfile.image-service
This PR moves centos base image from stream8 to stream 9 as well as stream8 is EOL
=> [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

Dockerfile.image-service
This PR moves centos base image from stream8 to stream 9 as well as stream8 is EOL
=> [release-ocm-2.8] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

Dockerfile.image-service, integration_test/images_test.go, main.go, pkg/isoeditor/ignition.go, pkg/isoeditor/isoutil.go, pkg/isoeditor/rhcos.go, pkg/isoeditor/rhcos_test.go
As part of integrating the nmstate service into our flow, it's necessary to include the `nmstatectl` binary in the initrd for minimal ISO cases. This ensures that the pre-network-manager-config service can run the nmstate service early during the boot process, allowing the nmstate YAML to be applied as keyfiles.
Note: In a later phase, I will fetch the binary from the rootfs. This PR is just the initial implementation. See - [MGMT-18577](https://issues.redhat.com/browse/MGMT-18577)
To verify this, I used test-infra's Minikube, generated and downloaded the minimal ISO, then interrupted the boot process to confirm that the `nmstate.img` was successfully added to the initrd.
/cc @carbonin 
/cc @jhernand 
/cc @AlonaKaplan
=> MGMT-18578 - Add nmstatectl binary to initrd in minimal ISO for OCP 4.13-4.17 (x86_64 architecture)

.github/dependabot.yml
Improve dependabot groups.
Allowing security update in a separate group give us smaller change ( minor version change ) which will be easier to auto merge.
/cc @
/cc @
=> MGMT-18466: improve depndabot grouping

build_deploy.sh
We want to change app-interface to deploy the images that Konflux builds and by default Konflux uses the full commit sha as the tag.
In order to avoid issues with telling app-interface to use the full commit sha, I am updating build_deploy.sh to push both the full sha and the short sha as image tags.
Part of [MGMT-19128](https://issues.redhat.com//browse/MGMT-19128)
=> MGMT-19128: Migrate assisted-image-service to Konflux

pkg/isoeditor/isoutil.go, pkg/isoeditor/isoutil_test.go
Analyzing the problem we had reported about the creation of hybrid images (boot from CD and USB sticks) in the appliance project I have found a problem with the calculation of the EFI image sectors in the ElTorito information table.
Until now, to calculate the number of sectors used we were using a block of 2048 bits (sector size for an iso9660), but however it seems that the sector used for the calculation is actually 512 bytes.
This difference in sectors causes the `isohybrid`, when preparing the image, to create an EFI partition that is too small and cut the bootloader:
```shell
$ ls -lh /mnt/images/efiboot.img                                                        
-rw-r--r--. 1 root root 4.9M Oct 22 10:36 /mnt/images/efiboot.img
$ fdisk -l appliance.iso
Disk appliance.iso: 37.8 GiB, …
```
=> MGMT-18693: Change efiLoadSectors block size

Dockerfile.image-service, Dockerfile.image-service-build, pkg/isoeditor/nmstate_handler.go
Following this thread - https://redhat-internal.slack.com/archives/C02AX10EQJW/p1731502735110969 , since we can't use the epel pkg, specifically the p7zip pkg, we are now using CPIO to extract the root filesystem.
/cc @carbonin 
/cc @danielerez
=> MGMT-19271: Using CPIO as an alternative approach to extract the rootfs instead of p7zip

.tekton/assisted-image-service-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-image-service-mce-downstream-2-13-push.yaml, .tekton/assisted-image-service-mce-downstream-main-pull-request.yaml, .tekton/assisted-image-service-mce-downstream-main-push.yaml
A lot of time our pipelines as well as other teams' pipelines are stuck because they are unable to provision hosts with different architectures to build the images.
Because we currently don't use the multi-arch images we build with konflux, we will stop building multi-arch for now and readd those architectures when we need them.
/cc @pastequo 
/cc @
Part-of [MGMT-19507](https://issues.redhat.com//browse/MGMT-19507)
=> MGMT-19507: Stop using multi-arch builds in konflux

Dockerfile.image-service-mce
Currently our base image use ubi9 and MintMaker wants to upgrade it to 9.5, because MintMaker looks at the repo and tries to upgrade to the newest tag.
This changes the base image to use a repo that is just for rhel9.4.
/cc @
/cc @
Part-of [MGMT-19381](https://issues.redhat.com//browse/MGMT-19381)
=> MGMT-19381: Change downstream base image to rhel9.4 instead of ubi9

.tekton/assisted-image-service-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-image-service-mce-downstream-2-13-push.yaml, .tekton/assisted-image-service-mce-downstream-main-pull-request.yaml, .tekton/assisted-image-service-mce-downstream-main-push.yaml, .tekton/assisted-image-service-saas-main-pull-request.yaml, .tekton/assisted-image-service-saas-main-push.yaml
The current buildah images in the tekton pipelines accidentally create the SBOM with CycloneDX 1.6 which causes a violation in the ECP check.
These new images set the CycloneDX to 1.5 as the ECP check expects.
/cc @pastequo
/cc @
=> NO-ISSUE: Update buildah image to fix a bug with SBOM

.dockerignore, Dockerfile.image-service
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
CI tests image building, also built locally.
/cc @pastequo 
/cc @rccrdpccl  
No Links
=> MGMT-19819: Add the commit reference from which the image is built to the image

deploy/template.yaml
[MGMT-19211](https://issues.redhat.com//browse/MGMT-19211): reduce assisted-image-service boot time
Resource request and limit values got parameterized so those can be configured in staging.
-
/cc @rccrdpccl
=> MGMT-19211: reduce assisted-image-service boot time

deploy/template.yaml
[MGMT-19211](https://issues.redhat.com//browse/MGMT-19211): set reasonable resource limits for the pods
Setting the CPU limit to 1 is expected to prevent the pods from throttling and so improve the performance significantly during the startup phase.
Several resource limit values were performance tested with assisted-test-infra cluster and compared to current settings.
Multiple tests were executed using different resource limit combinations, and measured the time needed both for downloading the images and creating the minimal ISOs. All cases used the full set of 30 images just like in the staging env.
**Findings**
- Download time is not affected by memory limit
- Download time starts to increase with CPU limit values under 1. At current limit (200m) the download time gets twice the no …
=> MGMT-19211: set reasonable resource limits for the pods

.dockerignore, Dockerfile.image-service
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
=> [release-ocm-2.11] MGMT-19819: Add the commit reference from which the image is built to the image

deploy/template.yaml
[MGMT-19211](https://issues.redhat.com//browse/MGMT-19211): mount path values were not populated from parameters, which blocked the pods from starting, so using static values instead
/cc @rccrdpccl
=> MGMT-19211: use static values for volume mount paths

internal/handlers/boot_artifacts.go, internal/handlers/boot_artifacts_test.go
Fixing artifact name issue for vmlinuz in  latest rhelVersions ( starting from 9.6 ) 
- Updated boot_artifacts.go to change artifact name to vmliuz from kernel.img based on RHCOS version
-  Starting from RHEL9.6 , artifact name for kernel has  changed to vmliuz from kernel.img. this is breaking the existing flow in Hosted Control Plane and Assisted Installer.
- Updated the logic to change the artifact name based the RHEL Version. 
- Built a test image with assisted-image-service 
- Using this test image, created AgentServiceConfig and InfraEnv objects, and validated the images generated in InfraEnv.
@AmadeusPodvratnik 
cc @v78singh 
cc @phani2898 
https://issues.redhat.com/browse/OCPBUGS-51209
=> OCPBUGS-51209:  Fixing artifact name issue for vmlinuz in  latest rhelVersions

internal/handlers/initrd.go, internal/handlers/initrd_addrsize_test.go, internal/handlers/initrd_test.go, pkg/imagestore/imagestore.go, pkg/imagestore/imagestore_test.go, pkg/imagestore/mock_imagestore.go, pkg/isoeditor/mock_editor.go, pkg/isoeditor/mock_nmstate_handler.go, pkg/isoeditor/nmstate_handler.go, pkg/isoeditor/nmstate_handler_test.go, pkg/isoeditor/rhcos.go, pkg/isoeditor/rhcos_test.go
When booting via PXE with static networking, connectivity could not be established, which resulted in failure to fetch the rootfs. The root cause is the absence of nmstatectl in the initrd. This PR solve this.
**Notes:** 
1. This PR triggered a high-severity warning from Snyk related to os.Open. Although the suggested mitigation was applied in the PR, the warning still persists. That said, it doesn’t appear to be a real security risk because:
-  The input parameters (version and arch) are validated.
- Even if someone tried to craft values to access files outside the intended directory, an additional check was added to ensure that the parent directory of nmstatectlPath matches the expected working directory - and the code rejects the path if it doesn’t.
2. The reason we're placing the …
=> MGMT-20597: Add nmstatectl to initrd for PXE provisioning
